---
products:

  opsman:
    product-version: "2.7.3"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-gcp-*.yml"

  pks:
    product-version: "1.4.2"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: google

  harbor:
    product-version: "1.8.3"
    pivnet-product-slug: harbor-container-registry
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: google