---
products:

  opsman:
    product-version: "2.7.4"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-gcp-*.yml"

  # PAS
  pas:
    product-version: "2.6.5"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"            # For full fledged PAS, use "cf-*.pivotal"
    stemcell-iaas: google                        # 1) uncomment it if one desires the latest applicable stemcell for the product, or
  pas-stemcell:                                  # 2) use this session to specify exact stemcell you want
    product-version: "315.99"                    # applicable stemcell range: 315.93–315.99
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"