---

products:

  opsman:
    product-version: "2.8.3"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-vsphere-*.ova"

  pks:
    product-version: "1.6.1"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
  pks-stemcell:
    product-version: "456.51"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"

  wavefront-nozzle:
    product-version: 2.0.0
    pivnet-product-slug: wavefront-nozzle
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "wavefront-nozzle-*.pivotal"
    stemcell-iaas: google
  wavefront-nozzle-stemcell:
    product-version: "250.183"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"